# Generated by Django 3.2 on 2024-06-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_aisle_upright'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upright',
            old_name='upright',
            new_name='aisle',
        ),
    ]
