# Generated by Django 4.2.13 on 2024-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_assignitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignitem',
            name='barcode_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
