# Generated by Django 3.2 on 2024-06-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='username'),
        ),
    ]
