# Generated by Django 3.2 on 2024-06-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Cost',
            new_name='Price',
        ),
    ]
