# Generated by Django 3.2 on 2024-06-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_cost_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='UPC_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
